fixed navigation bar and added about us view
starboy-jb/BShoppy pull request #2
Opened 2020-10-02 16:37 UTC by cyclades1

About us information can be added now to the page and navigation is also fixed

2020-10-02 17:15 UTC, lowjack1 requested changes
All pyc files are python cached files. They are not needed. Please remove them add them to *.pyc to .gitignore file.

2020-10-03 07:10 UTC, cyclades1 commented
I have added a gitignore for the cache files in project

2020-10-03 07:48 UTC, lowjack1 approved these changes

2020-10-10 06:37 UTC, starboy-jb approved these changes

2020-10-10 06:38 UTC, merged